USE master;

DROP DATABASE ATX2Plantões;

CREATE DATABASE ATX2Plantões;

USE ATX2Plantões;

CREATE TABLE Setor
	(
		idSetor INT NOT NULL CONSTRAINT pkidSetor PRIMARY KEY IDENTITY,
		nomeSetor NVARCHAR(20)
	);
	
CREATE TABLE Cargo
	(
		idCargo INT NOT NULL CONSTRAINT pkidCargo PRIMARY KEY IDENTITY,
		fkidSetor INT NOT NULL CONSTRAINT cargoidSetor
			FOREIGN KEY REFERENCES Setor(idSetor)
				ON DELETE CASCADE
				ON UPDATE CASCADE,
		nomeCargo NVARCHAR(20) NOT NULL
	);
	
CREATE TABLE Turno
	(
		idTurno INT NOT NULL CONSTRAINT pkidTurno PRIMARY KEY IDENTITY,
		nomeTurno NVARCHAR(20) NOT NULL,
		horaInício TIME NOT NULL,
		horaIntervalo TIME NOT NULL,
		tempoIntervalo TIME NOT NULL,
		horaTérmino TIME NOT NULL,
		horasFolga TIME NOT NULL
	);

CREATE TABLE Pessoa
	(
		idPessoa INT NOT NULL CONSTRAINT pkidPessoa PRIMARY KEY IDENTITY,
		nome NVARCHAR(100) NOT NULL,
		cPF DECIMAL(11,0) NOT NULL UNIQUE,
		dataAtualização DATETIME DEFAULT CURRENT_TIMESTAMP,
		dataCadastro DATETIME DEFAULT CURRENT_TIMESTAMP,
		fkidCargo INT NOT NULL CONSTRAINT pessoaidCargo
			FOREIGN KEY REFERENCES Cargo(idCargo)
				ON DELETE CASCADE
				ON UPDATE CASCADE,
		observações NVARCHAR(250) NULL,
		systemUser NVARCHAR(20) NOT NULL,
		senha NVARCHAR(30) NOT NULL,
		userAdmin BIT NOT NULL
	);

CREATE TABLE Plantão
	(
		idPlantão INT NOT NULL CONSTRAINT pkidPlantão PRIMARY KEY IDENTITY,
		fkidPessoa INT NOT NULL CONSTRAINT plantãoidPessoa
			FOREIGN KEY REFERENCES Pessoa(idPessoa)
				ON DELETE CASCADE
				ON UPDATE CASCADE,
		fkidTurno INT NOT NULL CONSTRAINT fkidTurno
			FOREIGN KEY REFERENCES Turno(idTurno)
				ON DELETE CASCADE
				ON UPDATE CASCADE,
		dataInício DATE NOT NULL,
		codPlantão INT NOT NULL
	);
